---

- name: "5.1 | GPO | Ensure Print Spooler (Spooler) is set to Disabled Domain Controller."
  when:
    - win16cis_rule_5_1
    - "'(Skipped)' not in item"
  tags:
    - level1-domaincontroller
    - rule_5.1
    - patch
    - printer
    - gpo
  ansible.windows.win_shell: |
    $gpoName = "{{ item }}"
    $registryKeyPath = "HKLM\SYSTEM\CurrentControlSet\Services\Spooler"
    $registryValueName = "Start"
    $type = "DWORD"
    $desiredValue = 4

    # Get the current value of the registry key in the GPO
    $currentValue = (Get-GPRegistryValue -Name $gpoName -Key $registryKeyPath -ValueName $registryValueName -ErrorAction SilentlyContinue).Value

    # Check if the current value is equal to the desired value
    if ($currentValue -ne $desiredValue) {
        # If not, set the registry value to the desired value
        Set-GPRegistryValue -Name $gpoName -Key $registryKeyPath -ValueName $registryValueName -Type $type -Value $desiredValue
        Write-Output "Patched"
    } else {
        Write-Output "No Change Needed"
    }
  loop:
    - "{{ win16cis_l1_dc_gpo_name ~ ( '(Skipped)' if not win16cis_l1_dc_gpo else '' ) }}"
  loop_control:
    label: "{{ item }}"
  changed_when: '"Patched" in rule_5_1_results.stdout'
  register: rule_5_1_results

- name: "5.2 | GPO | Ensure Print Spooler (Spooler) is set to Disabled Member Server."
  when:
    - win16cis_rule_5_2
    - "'(Skipped)' not in item"
  tags:
    - level2-memberserver
    - rule_5.2
    - patch
    - printer
    - gpo
  ansible.windows.win_shell: |
    $gpoName = "{{ item }}"
    $registryKeyPath = "HKLM\SYSTEM\CurrentControlSet\Services\Spooler"
    $registryValueName = "Start"
    $type = "DWORD"
    $desiredValue = 4

    # Get the current value of the registry key in the GPO
    $currentValue = (Get-GPRegistryValue -Name $gpoName -Key $registryKeyPath -ValueName $registryValueName -ErrorAction SilentlyContinue).Value

    # Check if the current value is equal to the desired value
    if ($currentValue -ne $desiredValue) {
        # If not, set the registry value to the desired value
        Set-GPRegistryValue -Name $gpoName -Key $registryKeyPath -ValueName $registryValueName -Type $type -Value $desiredValue
        Write-Output "Patched"
    } else {
        Write-Output "No Change Needed"
    }
  loop:
    - "{{ win16cis_l2_ms_gpo_name ~ ( '(Skipped)' if not win16cis_l2_ms_gpo else '' ) }}"
  loop_control:
    label: "{{ item }}"
  changed_when: '"Patched" in rule_5_2_results.stdout'
  register: rule_5_2_results
