---

- name: Display Banner
  ansible.builtin.debug:
      msg: "{{ lockdown_banner.split('\n') }}"
  tags:
      - always

- name: Gather Distribution Info
  ansible.builtin.setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  ansible.builtin.assert:
      that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('(Microsoft Windows Server 2016)')
      success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
      fail_msg: "This role can only be run against Windows Server 2016 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(min_ansible_version, '>=')
      msg: You must use Ansible {{ min_ansible_version }} or greater
  tags:
      - always

- name: Setup for Audit
  ansible.builtin.import_tasks: setup_audit.yml
  when: setup_audit
  tags:
      - setup_audit

- name: Run Audit
  ansible.builtin.import_tasks: run_audit.yml
  when: run_audit
  vars:
      audit_time: pre
  tags:
      - run_audit

- name: Execute the section 1 tasks
  ansible.builtin.import_tasks: section01.yml
  when: win16cis_section01
  tags:
      - section01

- name: Execute the section 2 tasks
  ansible.builtin.import_tasks: section02.yml
  when: win16cis_section02
  tags:
      - section02

- name: Execute the section 9 tasks
  ansible.builtin.import_tasks: section09.yml
  when: win16cis_section09
  tags:
      - section09

- name: Execute the section 17 tasks
  ansible.builtin.import_tasks: section17.yml
  when: win16cis_section17
  tags:
      - section17

- name: Execute the section 18 tasks
  ansible.builtin.import_tasks: section18.yml
  when: win16cis_section18
  tags:
      - section18

- name: Execute the section 19 tasks
  ansible.builtin.import_tasks: section19.yml
  when: win16cis_section19
  tags:
      - section19

- name: Run Audit
  ansible.builtin.import_tasks: run_audit.yml
  when:
      - run_audit
  vars:
      audit_time: post
  tags:
      - run_audit

- name: Show Audit Summary
  ansible.builtin.debug:
      msg: "{{ audit_results.split('\n') }}"
  when:
      - run_audit
  tags:
      - run_audit
