---
# Copied pre and post to capture output files.
- name: copy the template used by ansible for consistent checks
  ansible.windows.win_template:
      src: templates/ansible_vars_goss.yml.j2
      dest: "{{ goss_vars_path }}"
  when:
      - audit_time == 'pre'

- name: Run the goss audit
  ansible.windows.win_shell: "{{ run_audit_script }} -auditbin {{ audit_capture_path }}{{ goss_exe }} -auditdir {{ audit_capture_path }} -varsfile {{ ansible_hostname }}.yml -outfile {{ audit_results_file }}"
  failed_when: false

- name: Capture the pre remediation audit data summary
  block:
      - name: Capture pre remediation audit data
        ansible.windows.win_command: "powershell.exe -noninteractive -noprofile -command (Get-Content {{ audit_results_file }} | ConvertFrom-Json).summary"
        register: pre_audit
        changed_when: false

      - name: Capture pre-audit result
        ansible.builtin.set_fact:
            pre_audit_summary: "{{ pre_audit.stdout }}"
        vars:
            summary: 'summary."summary-line"'
  when:
      - audit_time == 'pre'

- name: Capture the post remediation audit data summary
  block:
      - name: Capture post remediation audit data
        ansible.windows.win_command: "powershell.exe -noninteractive -noprofile -command (Get-Content {{ audit_results_file }} | ConvertFrom-Json).summary"
        register: post_audit
        changed_when: false

      - name: Capture post-audit result
        ansible.builtin.set_fact:
            post_audit_summary: "{{ post_audit.stdout }}"
        vars:
            summary: 'summary."summary-line"'
  when:
      - audit_time == 'post'
