---
- name: "SCORED | 19.1.3.1 | PATCH | (L1) Ensure 'Enable screen saver' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.1.3.1 | PATCH | (L1) Ensure 'Enable screen saver' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaveActive
            data: 1
            type: string

      - name: "SCORED | 19.1.3.1 | PATCH |(L1) Ensure 'Enable screen saver' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaveActive
            data: 1
            type: string
  when:
      - rule_19_1_3_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.1.3.1
      - patch

- name: "SCORED | 19.1.3.2 | PATCH | (L1) Ensure 'Force specific screen saver: Screen saver executable name' is set to 'Enabled: scrnsave.scr'"
  block:
      - name: "SCORED | 19.1.3.2 | PATCH | (L1) Ensure 'Force specific screen saver: Screen saver executable name' is set to 'Enabled: scrnsave.scr'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: SCRNSAVE.EXE
            data: scrnsave.scr
            type: string

      - name: "SCORED | 19.1.3.2 | PATCH | (L1) Ensure 'Force specific screen saver: Screen saver executable name' is set to 'Enabled: scrnsave.scr'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: SCRNSAVE.EXE
            data: scrnsave.scr
            type: string
  when:
      - rule_19_1_3_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.1.3.2
      - patch

- name: "SCORED | 19.1.3.3 | PATCH | (L1) Ensure 'Password protect the screen saver' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.1.3.3 | PATCH | (L1) Ensure 'Password protect the screen saver' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaverIsSecure
            data: 1
            type: string

      - name: "SCORED | 19.1.3.3 | PATCH | (L1) Ensure 'Password protect the screen saver' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaverIsSecure
            data: 1
            type: string
  when:
      - rule_19_1_3_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.1.3.3
      - patch

- name: "SCORED | 19.1.3.4 | PATCH | (L1) Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
  block:
      - name: "SCORED | 19.1.3.4 | PATCH | (L1) Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaveTimeOut
            data: 900
            type: string

      - name: "SCORED | 19.1.3.4 | PATCH | (L1) Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
            name: ScreenSaveTimeOut
            data: 900
            type: string
  when:
      - rule_19_1_3_4
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.1.3.4
      - patch

- name: "SCORED | 19.5.1.1 | PATCH | (L1) Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.5.1.1 | PATCH | (L1) Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
            name: NoToastApplicationNotificationOnLockScreen
            data: 1
            type: dword

      - name: "SCORED | 19.5.1.1 | PATCH | (L1) Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
            name: NoToastApplicationNotificationOnLockScreen
            data: 1
            type: dword
  when:
      - rule_19_5_1_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.5.1.1
      - patch

- name: "SCORED | 19.6.6.1.1 | PATCH | (L2) Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.6.6.1.1 | PATCH | (L2) Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Assistance\Client\1.0
            name: NoImplicitFeedback
            data: 1
            type: dword

      - name: "SCORED | 19.6.6.1.1 | PATCH | (L2) Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Assistance\Client\1.0
            name: NoImplicitFeedback
            data: 1
            type: dword
  when:
      - rule_19_6_6_1_1
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_19.6.6.1.1
      - patch

- name: "SCORED | 19.7.4.1 | PATCH | (L1) Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
  block:
      - name: "SCORED | 19.7.4.1 | PATCH | (L1) Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
            name: SaveZoneInformation
            data: 2
            type: dword

      - name: "SCORED | 19.7.4.1 | PATCH | (L1) Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
        win_regedit:
            path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
            name: SaveZoneInformation
            data: 2
            type: dword
  when:
      - rule_19_7_4_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.4.1
      - patch

- name: "SCORED | 19.7.4.2 | PATCH | (L1) Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.4.2 | PATCH | (L1) Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Microsoft\Windows\Currentversion\Policies\Attachments
            name: ScanWithAntiVirus
            data: 3
            type: dword

      - name: "SCORED | 19.7.4.2 | PATCH | (L1) Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Microsoft\Windows\Currentversion\Policies\Attachments
            name: ScanWithAntiVirus
            data: 3
            type: dword
  when:
      - rule_19_7_4_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.4.2
      - patch

- name: "SCORED | 19.7.7.1 | PATCH | (L1) Ensure 'Configure Windows spotlight on lock screen' is set to Disabled'"
  block:
      - name: "SCORED | 19.7.7.1 | PATCH | (L1) Ensure 'Configure Windows spotlight on lock screen' is set to Disabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
            name: ConfigureWindowsSpotlight
            data: 2
            type: dword

      - name: "SCORED | 19.7.7.1 | PATCH | (L1) Ensure 'Configure Windows spotlight on lock screen' is set to Disabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
            name: ConfigureWindowsSpotlight
            data: 2
            type: dword
  when:
      - rule_19_7_7_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.7.1
      - patch

- name: "SCORED | 19.7.7.2 | PATCH | (L1) Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.7.2 | PATCH | (L1) Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableThirdPartySuggestions
            data: 1
            type: dword

      - name: "SCORED | 19.7.7.2 | PATCH | (L1) Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableThirdPartySuggestions
            data: 1
            type: dword
  when:
      - rule_19_7_7_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.7.2
      - patch

- name: "SCORED | 19.7.7.3 | PATCH | (L2) Ensure 'Do not use diagnostic data for tailored experiences' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.7.3 | PATCH | (L2) Ensure 'Do not use diagnostic data for tailored experiences' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableTailoredExperiencesWithDiagnosticData
            data: 1
            type: dword

      - name: "SCORED | 19.7.7.3 | PATCH | (L2) Ensure 'Do not use diagnostic data for tailored experiences' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableTailoredExperiencesWithDiagnosticData
            data: 1
            type: dword
  when:
      - rule_19_7_7_3
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_19.7.7.3
      - patch

- name: "SCORED | 19.7.7.4 | PATCH | (L2) Ensure 'Turn off all Windows spotlight features' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.7.4 | PATCH | (L2) Ensure 'Turn off all Windows spotlight features' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableWindowsSpotlightFeatures
            data: 1
            type: dword

      - name: "SCORED | 19.7.7.4 | PATCH | (L2) Ensure 'Turn off all Windows spotlight features' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
            name: DisableWindowsSpotlightFeatures
            data: 1
            type: dword
  when:
      - rule_19_7_7_4
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_19.7.7.4
      - patch

- name: "SCORED | 19.7.26.1 | PATCH | (L1) Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.26.1 | PATCH | (L1) Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Microsoft\Windows\Currentversion\Policies\Explorer
            name: NoInplaceSharing
            data: 1
            type: dword

      - name: "SCORED | 19.7.26.1 | PATCH | (L1) Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
            name: NoInplaceSharing
            data: 1
            type: dword
  when:
      - rule_19_7_26_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.26.1
      - patch

- name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  block:
      - name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Installer
            name: AlwaysInstallElevated
            data: 0
            type: dword

      - name: "SCORED | 19.7.41.1 | PATCH | (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windows\Installer
            name: AlwaysInstallElevated
            data: 0
            type: dword
  when:
      - rule_19_7_41_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.41.1
      - patch

- name: "SCORED | 19.7.45.2.1 | PATCH | (L2) Ensure 'Prevent Codec Download' is set to 'Enabled'"
  block:
      - name: "SCORED | 19.7.45.2.1 | PATCH | (L2) Ensure 'Prevent Codec Download' is set to 'Enabled'"
        win_regedit:
            path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windowsmediaplayer
            name: PreventCodecDownload
            data: 1
            type: dword

      - name: "SCORED | 19.7.45.2.1 | PATCH | (L2) Ensure 'Prevent Codec Download' is set to 'Enabled'"
        win_regedit:
            path: HKCU:\Software\Policies\Microsoft\Windowsmediaplayer
            name: PreventCodecDownload
            data: 1
            type: dword
  when:
      - rule_19_7_45_2_1
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_19.7.45.2.1
      - patch
