---

- name: Create directory for goss
  ansible.windows.win_file:
      path: "{{ audit_capture_path }}"
      state: directory

- name: download goss binary
  ansible.windows.win_get_url:
      url: "{{ goss_download_url }}"
      dest: "{{ audit_capture_path }}{{ goss_exe }}"
      checksum: "{{ goss_dl_sha }}"
      checksum_algorithm: sha256
  when:
      - download_audit_exe

- name: copy goss binary
  ansible.windows.win_copy:
      src: "{{ goss_copy_src }}"
      dest: "{{ audit_capture_path }}{{ goss_exe }}"
  when:
      - copy_audit_exe

- name: download goss config
  ansible.windows.win_get_url:
      url: "{{ goss_conf_url }}"
      dest: "{{ audit_capture_path }}goss_conf.zip"
  register: audit_downloaded
  when:
      - download_goss_config

- name: Unzip goss config
  community.windows.win_unzip:
      src: "{{ audit_capture_path }}goss_conf.zip"
      dest: "{{ audit_capture_path }}"
  when:
      - download_goss_config
      - audit_downloaded.changed

- name: Rename Goss Config Folder
  ansible.windows.win_shell: Rename-Item {{ goss_conf_unzipped_dir }} {{ audit_scripts_dir }}
  when:
      - download_goss_config
      - audit_downloaded.changed
