---

- name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords."
  when: win16cis_rule_1_1_1
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.1
    - patch
    - password
  block:
    - name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords. | Set Variable."
      when: win16cis_max_passwords_saved == 24
      community.windows.win_security_policy:
        section: System Access
        key: PasswordHistorySize
        value: "{{ win16cis_max_passwords_saved }}"

    - name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords. | Check for more than 24 saved passwords warning."
      when:
        - win16cis_max_passwords_saved > 24 or
          win16cis_max_passwords_saved <= 23
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of maximum passwords set in win16cis_max_passwords_saved please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords. | Set warning count"
      vars:
        warn_control_id: '1.1.1'
      when:
        - win16cis_max_passwords_saved > 24 or
          win16cis_max_passwords_saved <= 23
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0"
  when: win16cis_rule_1_1_2
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.2
    - patch
    - password
  block:
    - name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0. | Set Variable."
      when:
        - win16cis_maximum_password_age <= 365
        - win16cis_maximum_password_age > 0
        - win16cis_maximum_password_age > win16cis_minimum_password_age
      community.windows.win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: "{{ win16cis_maximum_password_age }}"

    - name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0. | Warning check for maximum password age time."
      when:
        - win16cis_maximum_password_age > 365 or
          win16cis_maximum_password_age == 0
        - win16cis_maximum_password_age < win16cis_minimum_password_age
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid age set for win16cis_maximum_password_age please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."
          - "Also verify your win16cis_maximum_password_age is more then the win16cis_minimum_password_age"

    - name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0. | Set warning count."
      vars:
        warn_control_id: '1.1.2'
      when:
        - win16cis_maximum_password_age > 365 or
          win16cis_maximum_password_age == 0
        - win16cis_maximum_password_age < win16cis_minimum_password_age
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.1.3 | PATCH | Ensure Minimum password age is set to 1 or more days"
  when: win16cis_rule_1_1_3
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.3
    - patch
    - password
  block:
    - name: "1.1.3 | PATCH | Ensure Minimum password age is set to 1 or more days. | Set Variable."
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordAge
        value: "{{ win16cis_minimum_password_age }}"
      when:
        - win16cis_minimum_password_age <= 364 or
          win16cis_minimum_password_age > 0
        - win16cis_minimum_password_age < win16cis_maximum_password_age

    - name: "1.1.3 | AUDIT | Ensure Minimum password age is set to 1 or more days. | Warning check for minimum password age."
      when:
        - win16cis_minimum_password_age > 364 or
          win16cis_minimum_password_age == 0
        - win16cis_minimum_password_age > win16cis_maximum_password_age
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid age set for win16cis_maximum_password_age please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."
          - "Also verify your win16cis_minimum_password_age is less then the win16cis_maximum_password_age"

    - name: "1.1.3 | AUDIT | Ensure Minimum password age is set to 1 or more days. | Set warning count."
      vars:
        warn_control_id: '1.1.3'
      when:
        - win16cis_minimum_password_age > 364 or
          win16cis_minimum_password_age == 0
        - win16cis_minimum_password_age > win16cis_maximum_password_age
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters"
  when: win16cis_rule_1_1_4
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.4
    - patch
    - password
  block:
    - name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters. | Set Variable."
      when: win16cis_minimum_password_length >= 14
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordLength
        value: "{{ win16cis_minimum_password_length }}"

    - name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters | Warning Check For Variable Standards."
      when: win16cis_minimum_password_length < 14
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid length set for win16cis_minimum_password_length please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters. | Set warning count."
      when: win16cis_minimum_password_length < 14
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '1.1.4'

- name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled."
  when: win16cis_rule_1_1_5
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.5
    - patch
    - password
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1

- name: "1.1.6 | PATCH | Ensure 'Store passwords using reversible encryption' is set to 'Disabled'"
  when:
    - win16cis_rule_1_1_6
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.1.6
    - patch
    - password
  community.windows.win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0

# THE FOLLOWING 4 CONTROLS WILL FAIL UNLESS THEY ARE IN THE FOLLOWING ORDER FOR LOCAL-BASED SystemS
# CONTROL 1.2.2, CONTROL 1.2.4, CONTROL 1.2.1, CONTROL 1.2.3
- name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0."
  when:
    - win16cis_rule_1_2_2
    - not prelim_win16cis_cloud_based_system
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.2
    - patch
    - account
  block:
    - name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set Variable."
      when:
        - win16cis_bad_login_lockout_count <= 5
        - win16cis_bad_login_lockout_count > 0
      community.windows.win_security_policy:
        section: System Access
        key: LockoutBadCount
        value: "{{ win16cis_bad_login_lockout_count }}"

    - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Verify Variable Not 0 or more then 5 warning."
      when:
        - win16cis_bad_login_lockout_count > 5 or
          win16cis_bad_login_lockout_count == 0
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of attempts set for win16cis_bad_login_lockout_count please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set warning count."
      vars:
        warn_control_id: '1.2.2'
      when:
        - win16cis_bad_login_lockout_count > 5 or
          win16cis_bad_login_lockout_count == 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes."
  when:
    - win16cis_rule_1_2_4
    - not prelim_win16cis_cloud_based_system
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.4
    - patch
    - account
  block:
    - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set Variable."
      when:
        - win16cis_account_lockout_counter_reset >= 15
        - win16cis_account_lockout_counter_reset <= win16cis_account_lockout_duration
      community.windows.win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: "{{ win16cis_account_lockout_counter_reset }}"

    - name: "1.2.4 | AUDIT | Ensure Reset account lockout counter after is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
      when:
        - win16cis_account_lockout_counter_reset > win16cis_account_lockout_duration or
          win16cis_account_lockout_counter_reset < 15
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win16cis_account_lockout_counter_reset please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.4 | AUDIT | Ensure Reset account lockout counter after is set to 15 or more minutes. | | Set warning count."
      vars:
        warn_control_id: '1.2.4'
      when:
        - win16cis_account_lockout_counter_reset > win16cis_account_lockout_duration or
          win16cis_account_lockout_counter_reset < 15
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes"
  when:
    - win16cis_rule_1_2_1
    - not prelim_win16cis_cloud_based_system
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_1.2.1
    - patch
    - account
  block:
    - name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes. | Set Variable"
      when: win16cis_account_lockout_duration >= 15
      community.windows.win_security_policy:
        section: System Access
        key: LockoutDuration
        value: "{{ win16cis_account_lockout_duration }}"

    - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
      when: win16cis_account_lockout_duration < 15
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of minutes set for win16cis_account_lockout_duration please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Set warning count."
      vars:
        warn_control_id: '1.2.1'
      when: win16cis_account_lockout_duration < 15
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.2.3 | PATCH | Ensure Allow Administrator account lockout is set to Enabled"
  when:
    - win16cis_rule_1_2_3
    - prelim_win16cis_is_domain_member
    - not prelim_win16cis_cloud_based_system
  tags:
    - level1-memberserver
    - rule_1.2.3
    - patch
    - password
  community.windows.win_security_policy:
    section: System Access
    key: AllowAdministratorLockout
    value: "{{ win16cis_allow_admin_account_lockout }}"
